### ISSUE TITLE
What about licencese type?

### ISSUE THREAD

**Issue by ktaranov** [Evdlaar/QueryStoreDashboard#4]
Hi, Enrico. Thanks for nifty reports. What about to add some open source license to your project (for example [MIT](https://github.com/ktaranov/sqlserver-kit/blob/master/LICENSE.md))?
If this possible just choose license type and I can help to properly add license to your repo including badge and README link.

**Comment by Evdlaar** [comment]
Good point!
I added a license file and merged your README.
Thank!
