### ISSUE TITLE
Replace .zip archive to .rdl files without version number (use git tags for it)

### ISSUE THREAD

**Issue by ktaranov** [Evdlaar/QueryStoreDashboard#5]
.rdl file just .xml document, why are you saving it in .zip archive (binary file)? Version control was created for storing different version of "plain" files. Maybe, you should remove .zip files and upload "plain" .rdl files to this repo?

**Comment by Evdlaar** [comment]
Hello,

Initially the files were stored as rdl on GitHub but GitHub adds information inside the rdl xml which makes them unusable inside SSMS. 
To avoid this I added the files as .zip.
