### ISSUE TITLE
Error messages when executing Instance Dashboard because of "." or "-" in Database Name

### ISSUE THREAD

**Issue by MichelZ** [Evdlaar/QueryStoreDashboard#7]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Error messages when executing Instance Dashboard

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via http://sqlfiddle.com/**
Use a database with either a "." or a "-" in its name
You will receive "Incorrect syntax near '-'."
and
"Could not find server '<databasename>' in sys.servers. Verify that the correct server name was specified. If necessary, execute the stored procedure sp_addlinkedserver to add the server to sys.servers."

**What is the expected behavior?**
No error

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
SQL2016, Windows 2012 R2

**Comment by HanShi00** [comment]
All datasets in the report that define a cursor by querying the sys.databases table must be modified to prevent the error when a database name contains a "." or "-".
original part of the query (declare cursor):    select [name] from sys.databases
corrected part of the query (declare cursor):   select QUOTENAME([name] from sys.databases
